# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.2

RUN elasticsearch-plugin install repository-s3
RUN elasticsearch-plugin install discovery-ec2
